### ISSUE TITLE
Plugin doesn't work with Discourse 3.5.0.beta2

### ISSUE THREAD

**Issue by chriscroome** [muhlisbc/discourse-images-guardian#4]
The [latest Discourse](https://meta.discourse.org/t/3-5-0-beta2-review-queue-welcome-banner-admin-interface-and-more/358151) doesn't work with this plugin with these settings in `containers/app.yml`:

```yaml
hooks:
    after_code:
    -   exec:
            cd: $home/plugins
            cmd:
            - git clone https://github.com/muhlisbc/discourse-images-guardian.git
            - erb /var/www/discourse/plugins/discourse-images-guardian/nginx.sample.conf.erb
                > /var/www/discourse/config/nginx.sample.conf
```

Rebuilding the container fails with:

```
** INCOMPATIBLE PLUGIN **

You are unable to start Discourse due to errors in the plugin at
/var/www/discourse/plugins/discourse-images-guardian

Please try removing this plugin and rebuilding again!
```

I did look at using the [Secure uploads](https://meta.discourse.org/t/disallow-anonymous-users-from-viewing-image-file-urls/40335/24) option, but this only works with uploads going to S3:

![Image](https://github.com/user-attachments/assets/e2713a1c-19e2-439c-b277-f29cbd3eb485)

Is there any chance the plugin could be made to work again @muhlisbc ? Thanks!
